[package]
name = "gamdam-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.57"
bytes = "1.2.1"
log = "0.4.17"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.21.2", features = ["process"] }
