[package]
name = "gamdam-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
bytes = "1.2.1"
clap = { version = "4.0.18", default-features = false, features = ["derive", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
futures = "0.3.24"
log = { version = "0.4.17", features = ["std"] }
relative-path = { version = "1.7.2", features = ["serde"] }
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
shell-words = "1.1.0"
tokio = { version = "1.21.2", features = ["fs", "io-std", "io-util", "macros", "process", "sync", "time"] }
tokio-serde = { version = "0.8.0", features = ["json"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
url = { version = "2.3.1", features = ["serde"] }
