[package]
name = "gamdam-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.57"
bytes = "1.2.1"
futures = "0.3.24"
log = "0.4.17"
relative-path = { version = "1.7.2", features = ["serde"] }
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.21.2", features = ["io-util", "process", "time"] }
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.4", features = ["codec"] }
url = { version = "2.3.1", features = ["serde"] }
