name: Test

on:
  push:
    branches:
      - master
  pull_request:
  #schedule:
  #  - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - minimal
          - stable
          - beta
          - nightly
        include:
          - os: macos-latest
            toolchain: stable
          - os: windows-latest
            toolchain: stable
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure Git identity
        # Needed for a couple tests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'ghactions@nil.nil'

      - name: Install Rust
        if: matrix.toolchain != 'minimal'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Determine minimal supported Rust
        if: matrix.toolchain == 'minimal'
        id: minimal-version
        run: |
          rust_version="$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].rust_version')"
          echo "msrv=$rust_version" >> "$GITHUB_OUTPUT"

      - name: Install minimal supported Rust
        if: matrix.toolchain == 'minimal'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.minimal-version.outputs.msrv }}

      - name: Activate cache
        if: github.actor != 'dependabot[bot]'
        uses: Swatinem/rust-cache@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '^3.8'

      - name: Install git-annex (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          python3 -m pip install --upgrade datalad-installer
          datalad-installer -l DEBUG --sudo ok neurodebian git-annex -m neurodebian

      - name: Install git-annex (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          python3 -m pip install --upgrade datalad-installer
          datalad-installer -l DEBUG --sudo ok git-annex -m brew

      - name: Install git-annex (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          python3 -m pip install --upgrade datalad-installer
          datalad-installer -l DEBUG --sudo ok git-annex -m datalad/git-annex:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build crate
        run: cargo build --all-targets --verbose

      - name: Test crate
        run: cargo test --verbose

  coverage:
    # This is separate from the main tests because cargo-llvm-cov doesn't run
    # doctests.
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure Git identity
        # Needed for a couple tests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'ghactions@nil.nil'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: llvm-tools

      - name: Activate cache
        if: github.actor != 'dependabot[bot]'
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Install git-annex
        run: |
          python3 -m pip install --upgrade datalad-installer
          datalad-installer -l DEBUG --sudo ok neurodebian git-annex -m neurodebian

      - name: Test with coverage
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Activate cache
        if: github.actor != 'dependabot[bot]'
        uses: Swatinem/rust-cache@v2

      - name: Check code
        run: cargo clippy --all-features --all-targets -- -Dwarnings

      - name: Check formatting
        run: cargo fmt --check

#  docs:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v4
#
#      - name: Install nightly Rust
#        uses: dtolnay/rust-toolchain@master
#        with:
#          toolchain: nightly
#
#      - name: Activate cache
#        if: github.actor != 'dependabot[bot]'
#        uses: Swatinem/rust-cache@v2
#
#      - name: Check docs
#        run: cargo doc --no-deps --all-features
#        env:
#          RUSTDOCFLAGS: -Dwarnings

# vim:set et sts=2:
